### ISSUE TITLE
debops-update fails

### ISSUE THREAD

**Issue by chymian** [debops/debops-tools#121]
debops-update is failing between 9/76 and 15/76

so, I dont know, whether github is to blame for the "timeout" or not.
I was pinging github in parallel and got roundtriptimes from 99 to 104 sec on this 25Mbit/s cable connection. so, the network-path seems to be ok.
I had this error on different occasions, but today, it's not giving me one successful update out of 20  attempts within an hour.
even edited the debops-update script to use http instead of https didn't change anything.

I get tow diff. errormsg.:

```
debops-update 
DebOps playbooks have been found in /home/guenter/.local/share/debops/debops-playbooks

Updating https://github.com/debops/ansible-apt [master] (1/76)
Updating https://github.com/debops/ansible-apt_preferences [master] (2/76)
Updating https://github.com/debops/ansible-auth [master] (3/76)
Updating https://github.com/debops/ansible-backporter [master] (4/76)
Updating https://github.com/debops/ansible-bootstrap [master] (5/76)
Updating https://github.com/debops/ansible-boxbackup [master] (6/76)
Updating https://github.com/debops/ansible-console [master] (7/76)
Updating https://github.com/debops/ansible-debops [master] (8/76)
Updating https://github.com/debops/ansible-dhcpd [master] (9/76)


fatal: unable to access 'https://github.com/debops/ansible-dhcpd/': gnutls_handshake() failed: Error in the pull function.
fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/usr/local/bin/debops-update", line 220, in <module>
    main(args.project_dir)
  File "/usr/local/bin/debops-update", line 212, in main
    fetch_or_clone_roles(roles_path, GALAXY_REQUIREMENTS)
  File "/usr/local/bin/debops-update", line 121, in fetch_or_clone_roles
    update_git_repository(destination_dir)
  File "/usr/local/bin/debops-update", line 147, in update_git_repository
    fetch_sha = subprocess.check_output(['git', 'rev-parse', 'FETCH_HEAD']).strip()
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'FETCH_HEAD']' returned non-zero exit status 128
```

and 

```
...
Updating http://github.com/debops/ansible-etc_services [master] (15/76)
fatal: unable to access 'https://github.com/debops/ansible-etc_services/': Failed to connect to github.com port 443: Connection timed out
fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/usr/local/bin/debops-update", line 221, in <module>
    main(args.project_dir)
  File "/usr/local/bin/debops-update", line 213, in main
    fetch_or_clone_roles(roles_path, GALAXY_REQUIREMENTS)
  File "/usr/local/bin/debops-update", line 122, in fetch_or_clone_roles
    update_git_repository(destination_dir)
  File "/usr/local/bin/debops-update", line 148, in update_git_repository
    fetch_sha = subprocess.check_output(['git', 'rev-parse', 'FETCH_HEAD']).strip()
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'FETCH_HEAD']' returned non-zero exit status 128
```

**Comment by drybjed** [comment]
Yes, this is usually GitHub's fault. Try a few more times, you should get all of them eventually.
