### ISSUE TITLE
debops-task script traceback

### ISSUE THREAD

**Issue by drybjed** [debops/debops-tools#73]
Looks like something is missing.

```
drybjed@helios ~/src/projects/helios/ % debops-task test -m setup
Traceback (most recent call last):
  File "/usr/local/bin/debops-task", line 5, in <module>
    pkg_resources.run_script('debops==0.1.0', 'debops-task')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/debops-0.1.0-py2.7.egg/EGG-INFO/scripts/debops-task", line 45, in <module>

TypeError: find_up() takes exactly 2 arguments (1 given)
```

Although, `debops-task` script is not essential - after one run of `debops`, Ansible configuration file is generated and you can use `ansible` command directly. So I suppose we could just remove `debops-task` and not worry about it.

**Comment by drybjed** [comment]
Pinging @htgoebel

**Comment by htgoebel** [comment]
Please merge #74 for fixing this.

**Comment by drybjed** [comment]
@htgoebel Thanks. Let's test it out before releasing a new version.
