### ISSUE TITLE
debops v0.2.0 fails to run on Yosemite

### ISSUE THREAD

**Issue by Marc-Whiteman** [debops/debops-tools#83]
$ debops
Traceback (most recent call last):
  File "/usr/local/bin/debops", line 162, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/debops", line 97, in main
    config = read_config(debops_root)
  File "/Library/Python/2.7/site-packages/debops/config.py", line 60, in read_config
    configfiles = _configfiles + [os.path.join(debops_root, DEBOPS_CONFIG)]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

That is from a dir with a .debops.cfg, ansible.cfg is not created.

**Comment by Marc-Whiteman** [comment]
Fixed with commit from:
https://github.com/debops/debops/commit/06750c1885c0338a642b873397fb4d8b2fe49548
